/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.application.form.other;

import GUI.application.exceptionHandler.ExceptionHandler;
import GUI.application.exceptionHandler.HibernateExceptionHandler;
import com.scrum.registrationsystem.entities.Fines;
import javax.swing.table.DefaultTableModel;
import com.scrum.registrationsystem.dao.FinesDAO;
/**
 *
 * @author acuri
 */
public class FormFines extends javax.swing.JPanel {
    private final FinesDAO finesManage;
    private static final String[] COLUMN_NAMES = {"id", "Cd. Empleado", "Descripcion", "Valor"};
    private final ExceptionHandler exceptionHandler;

    /**
     * Creates new form FinesForm
     */
    public FormFines() {
        initComponents();
        finesManage = new FinesDAO();
        exceptionHandler = new HibernateExceptionHandler();
        chargeTable();
    }

    private void chargeTable() {
	DefaultTableModel model = new DefaultTableModel(COLUMN_NAMES, 0);
	try {
            var fines = finesManage.getMultas();
            for (Fines fine : fines) {
		model.addRow(new Object[]{fine.getId(), fine.getUser().getFirstName() + " " + fine.getUser().getLastName(), fine.getDescripcion(), fine.getValorMulta()});
            }
	} catch (Exception e) {
            exceptionHandler.handleException(e);
	}
            jtblFines.setModel(model);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblFines = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jtblFines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblFines);

        jLabel1.setText("Multas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblFines;
    // End of variables declaration//GEN-END:variables
}
